version: '3.8'

services:
  redis-cache:
    image: redis:alpine
    env_file: ./.env
    ports:
      - $REDIS_CACHE_PORT:$REDIS_CACHE_PORT
    networks:
      - finance-manager-api-network

  postgres-db:
    image: postgres:alpine
    env_file: ./.env
    environment:
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_USER: $POSTGRES_DB_USER
      POSTGRES_PASSWORD: $POSTGRES_DB_PASSWORD
    ports:
      - $POSTGRES_DB_PORT:$POSTGRES_DB_PORT
    networks:
      - finance-manager-api-network
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

  finance-manager-api:
    build: .
    env_file: ./.env
    environment:
      JWT_SECRET: $JWT_SECRET
      JWT_ISSUER: $JWT_ISSUER
      JWT_EXPIRES: $JWT_EXPIRES
      SERVER_PORT: $SERVER_PORT
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: $REDIS_CACHE_PORT
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:$DB_PORT/$DB_NAME
      SPRING_DATASOURCE_USERNAME: $POSTGRES_DB_USER
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_DB_PASSWORD
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - finance-manager-api-network
    volumes:
      - finance-manager-api-logs:/logs
    depends_on:
      - postgres-db
      - redis-cache

volumes:
  postgres-db-data:
  finance-manager-api-logs:

networks:
  finance-manager-api-network:
    driver: bridge
